name: Deploy

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - run: pnpm install
      - name: Publish to Visual Studio Marketplace
        run: pnpm vsce publish --pat ${{ secrets.GITHUB_TOKEN }} --no-dependencies --target darwin-x64 --target darwin-arm64
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@release-2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*.vsix' 