name: Release

on:
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - run: pnpm install
      - run: pnpm run ci
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@release-2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*.vsix'
      - name: Publish to Visual Studio Marketplace
        run: pnpm vsce publish --pat ${{ secrets.VS_MARKETPLACE_TOKEN }} --no-dependencies --target darwin-x64 --target darwin-arm64
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          dependencies: false
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
